### PR TITLE
added XO

### PR DESCRIPTION
**Pull request by hrocha16**

### CODE REVIEW

**Review by vcapretz — APPROVED** [review]

**Comment by bukinoshita** [comment]
Thanks a lot @hrocha16! So glad to see your contribution. You might be missing [this](https://github.com/sindresorhus/eslint-config-xo-react#use-with-xo) tho.

JSX is supported by default but you need [eslint-config-xo-react](https://github.com/sindresorhus/eslint-config-xo-react#use-with-xo).

**Review by bukinoshita — CHANGES_REQUESTED** [review]
If possible to add eslint-config-xo-react

**Comment by hrocha16** [comment]
Added the eslint-config-xo-react, thanks a lot guys!

**Review by bukinoshita — APPROVED** [review]

**Comment by bukinoshita** [comment]
Nice work @hrocha16! Thanks so much 🎉 🌮 

https://github.com/bukinoshita/open-source/issues/5

**Pull request merged**
